version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:erbium
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: sudo apt-get update -qq
      - run:
          name: Install node dependencies
          command: yarn
      - run:
          name: Check code quality
          command: yarn run lint
      - run:
          name: Deploy to Heroku
          command: git push --force https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git +HEAD:refs/heads/master